version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"   # MQTT protocol
      - "9001:9001"   # WebSockets (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
